---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - -b
          - dev
          - -b
          - test
          - -b
          - stage
          - -b
          - perf
          - -b
          - prod
          - -b
          - nprd
          - -b
          - main
          - -b
          - master
      - id: pretty-format-json
  - repo: "https://github.com/gruntwork-io/pre-commit"
    rev: v0.1.22
    hooks:
      - id: shellcheck
      - id: terraform-fmt
      - id: terraform-validate
        args:
          - --args=-no-color
      - id: terragrunt-hclfmt
      - id: tflint
      - id: yapf
  - repo: "https://github.com/antonbabenko/pre-commit-terraform"
    rev: v1.77.3
    hooks:
      - id: terraform_docs
      - id: terraform_tfsec
